name: MakeABuilders
version: b0.2
main: org.MakeACakeStudios.MakeABuilders
commands:
  message:
    description: Отправить личное сообщение игроку.
    usage: /msg <игрок> <сообщение>
    aliases: [msg]
  reply:
    description: Ответить на последнее сообщение.
    usage: /r <сообщение>
    aliases: [r]
  message-sound:
    description: Изменение звука сообщений.
    usage: /msgs <звук>
    aliases: [msgs, msgsound]
  rename:
    description: Изменяет название предмета в руке.
    usage: /rename <новое_название>
    permission: MakeABuilders.rename
  goto:
    description: Телепортация игрока к заданным координатам.
    usage: /goto <world> <x> <y> <z>
    permission: MakeABuilders.goto
  back:
    description: Возвращение игрока.
    usage: /back
    permission: MakeABuilders.back
#  enchant:
#    description: Добавляет зачарования предмету в руке.
#    usage: /enchant <зачарование> <уровень>
#    permission: MakeABuilders.enchant
  mail:
    description: Отправить сообщение игроку оффлайн.
    usage: /mail <игрок> <сообщение>
    aliases: [m]
  mailcheck:
    description: Проверить непрочитанные сообщения.
    usage: /mailcheck
    aliases: [mc, mcheck]
  shrug:
    description: Смаг
    usage: /shrug
    aliases: [smugshrug]